# Big thanks to Chnossos! https://stackoverflow.com/a/30602701

# compiler
CC := g++
# folders
SRC_DIR := src
OBJ_DIR := obj
BIN_DIR := bin
# files
SRC := $(wildcard $(SRC_DIR)/*.cpp)
OBJ := $(SRC:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
BIN := $(BIN_DIR)/main
# compiler flags
CPPFLAGS := -Iinclude -MMD -MP
CFLAGS   := -Wall -O3 -std=c++17 -libstdc++
LDFLAGS  := -Llib -static-libstdc++
LDLIBS   := # no libraries

.PHONY: all clean

all: $(BIN)

$(BIN): $(OBJ) | $(BIN_DIR)
	$(CC) $(LDFLAGS) $^ $(LDLIBS) -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(BIN_DIR) $(OBJ_DIR):
	mkdir -p $@

clean:
	@$(RM) -rv $(BIN_DIR) $(OBJ_DIR)

# include makefile rules generated by the compiler
-include $(OBJ:.o=.d)
